name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.36.0', '5.34.1', '5.32.1', '5.30.3', '5.28.3', '5.26.3', '5.24.4', '5.22.4', '5.20.3', '5.18.4', '5.16.3', '5.14.4', '5.12.5', '5.10.1', '5.8.9' ]
        exclude:
          - runner: windows-latest
            perl: '5.36.0'
          - runner: windows-latest
            perl: '5.34.1'
          - runner: windows-latest
            perl: '5.28.3'
          - runner: windows-latest
            perl: '5.24.4'
          - runner: windows-latest
            perl: '5.22.4'
          - runner: windows-latest
            perl: '5.20.3'
          - runner: windows-latest
            perl: '5.18.4'
          - runner: windows-latest
            perl: '5.16.3'
          - runner: windows-latest
            perl: '5.14.4'
          - runner: windows-latest
            perl: '5.12.5'
          - runner: windows-latest
            perl: '5.10.1'
          - runner: windows-latest
            perl:  '5.8.9'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v3

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( matrix.runner == 'windows-latest' && 'strawberry' ) || 'default' }}
          install-modules-args: --notest --with-develop --with-configure --with-test

    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Modules
      run: |
        cpanm -v
        cpanm --installdeps --notest --with-configure .

    - name: Show Errors on Windows
      if:  ${{ failure() && matrix.runner == 'windows-latest' }}
      run: |
         ls -l C:/Users/
         ls -l C:/Users/RUNNER~1/
         cat C:/Users/runneradmin/.cpanm/work/*/build.log

    - name: Show Errors on Ubuntu
      if:  ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
      run: |
         cat /home/runner/.cpanm/work/*/build.log

    - name: Show Errors on OSX
      if:  ${{ failure() && startsWith( matrix.runner, 'macos-')}}
      run: |
         cat  /Users/runner/.cpanm/work/*/build.log

    - name: Run tests
      env:
        AUTHOR_TESTING: 1
        RELEASE_TESTING: 1
      run: |
        perl Makefile.PL
        make
        make test

